PowerAssert.MultipleAssertions.PolyAssertException: PolyAssert encountered 3 failures:
> ...\EndToEndTest.cs:483> I will report all the errors i saw when i get disposed
============================================================
ERROR ...\EndToEndTest.cs:484:
============================================================
IsTrue failed, expression was:

x == 5
. __
. |
| False
6

============================================================

============================================================
ERROR ...\EndToEndTest.cs:486:
============================================================
IsTrue failed, expression was:

x == 7
. __
. |
| False
6

============================================================

============================================================
ERROR ...\EndToEndTest.cs:487:
============================================================
Wah wah
============================================================

> ...\EndToEndTest.cs:488> PolyAssert.Log messages are only printed if the test fails

   at PowerAssert.MultipleAssertions.PolyAssert.StopIfErrorsHaveOccurred() in ...\PolyAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Dispose() in ...\PolyAssert.cs
   at PowerAssertTests.Approvals.EndToEndTest.PolyAssert() in ...\EndToEndTest.cs