PolyAssert encountered 3 failures:

   at PowerAssert.MultipleAssertions.PolyAssert.StopIfErrorsHaveOccurred() in ...\PolyAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Dispose() in ...\PolyAssert.cs
   at PowerAssertTests.Approvals.EndToEndTest.PolyAssert() in ...\EndToEndTest.cs


============================================================


> I will report all the errors i saw when i get disposed


============================================================
System.Exception: IsTrue failed, expression was:

x == 5
. __
. |
| False
6

   at PowerAssert.PAssert.IsTrue(Expression`1 expression) in ...\PAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.<>c__DisplayClass2_0.<IsTrue>b__0() in ...\PolyAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Try(Action action) in ...\PolyAssert.cs
============================================================



============================================================
System.Exception: IsTrue failed, expression was:

x == 7
. __
. |
| False
6

   at PowerAssert.PAssert.IsTrue(Expression`1 expression) in ...\PAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.<>c__DisplayClass2_0.<IsTrue>b__0() in ...\PolyAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Try(Action action) in ...\PolyAssert.cs
============================================================



============================================================
NUnit.Framework.AssertionException: Wah wah
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at PowerAssertTests.Approvals.EndToEndTest.<>c.<PolyAssert>b__61_0() in ...\EndToEndTest.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Try(Action action) in ...\PolyAssert.cs
============================================================


> PolyAssert.Log messages are only printed if the test fails